#!/usr/bin/env bash
# install load balancer

# Install HAproxy package
apt-get update
apt-get install haproxy -y

# Configure HAproxy to send traffic to web-01 and web-02
echo "frontend http
  bind *:80
  default_backend servers

backend servers
  balance roundrobin
  server web-01 91486-web-01:80 check
  server web-02 91486-web-02:80 check" > /etc/haproxy/haproxy.cfg

# Enable and start HAproxy service
systemctl enable haproxy
systemctl start haproxy

