#!/bin/bash

if [[ $# -eq 0 ]]; then
	echo "Usage: $0 <username>"
	exit 1
fi

username=$1
if id -u "$username" >/dev/null 2>"$1"; then
	su -c "whoami" "$username"
else
echo "User '$username' does not exit."
fi
